In [1]:
from peft import LoraConfig, TaskType, PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer
import json
from datasets import Dataset
from trl import SFTTrainer, SFTConfig, DPOTrainer, DPOConfig
from prompt import SYSTEM_PROMPT_CODE, SYSTEM_PROMPT_EVAL
import torch
import gc
import evaluate
from tqdm import tqdm
import re
import numpy as np
import os
from sentence_transformers import SentenceTransformer, util

/etc/python/sitecustomize.py:236: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  mod = _original_import(name, globals, locals, fromlist, level)

# Helper Functions

In [2]:
def parse_manual_function_call(text):
    """
    Manually parse JSON-formatted function calls from LLM output.
    Returns: (function_name, function_args) or None
    """
    found_functions = []

    # Remove <think> tag content
    text = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL)

    # Find JSON-formatted function calls
    # Pattern matches: {"function": "xxx", "args": {...}}
    json_pattern = r'\{["\']function["\']\s*:\s*["\'](\w+)["\']\s*,\s*["\']args["\']\s*:\s*(\{[^}]*\})\s*\}'
    matches = re.findall(json_pattern, text)
    for match in matches:
        function_name = match[0]
        args_str = match[1]
        found_functions.append((function_name, args_str))

    # Also try matching JSON in code blocks
    code_block_pattern = r'```json\s*\n\s*\{["\']function["\']\s*:\s*["\'](\w+)["\']\s*,\s*["\']args["\']\s*:\s*(\{[^}]*\})\s*\}\s*\n\s*```'
    matches = re.findall(code_block_pattern, text, re.DOTALL)
    for match in matches:
        function_name = match[0]
        args_str = match[1]
        if (function_name, args_str) not in found_functions:
            found_functions.append((function_name, args_str))

    return found_functions

In [3]:
def evaluate_sft_model(model_id, model_dir, eval_dataset, output_dir, include_accuracy=True):
    # Load the fine-tuned model and tokenizer
    base_model = AutoModelForCausalLM.from_pretrained(model_id, dtype=torch.bfloat16, device_map="auto")
    fine_tuned_model = PeftModel.from_pretrained(base_model, model_dir)
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    eval_model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
    
    # Define evaluation metrics
    metrics = evaluate.combine(['bleu', 'rouge', 'meteor'])
    bertscore = evaluate.load('bertscore')
    semantic_similarities = []
    if include_accuracy:
        accuracies = []

    for instance in tqdm(eval_dataset):
        # Tokenize input
        text = tokenizer.apply_chat_template(
            instance["messages"][:-1], add_generation_prompt=True, tokenize=False
        )
        model_inputs = tokenizer([text], return_tensors="pt").to(fine_tuned_model.device)

        # Generate response
        generated_ids = fine_tuned_model.generate(
            **model_inputs,
            max_new_tokens=2048
        )
        output_ids = generated_ids[0][len(model_inputs.input_ids[0]):]

        # Decode and extract model response
        generated_text = tokenizer.decode(output_ids, skip_special_tokens=True)
        
        # Get the ground truth response
        gt_text = instance['messages'][-1]['content']
        
        # Compute semantic similarity
        gt_embedding = eval_model.encode(gt_text, convert_to_tensor=True)
        generated_embedding = eval_model.encode(generated_text, convert_to_tensor=True)

        # Compute metrics against the reference response
        metrics.add(prediction=generated_text, reference=gt_text)
        bertscore.add(prediction=generated_text, reference=gt_text)
        semantic_similarities.append(util.pytorch_cos_sim(gt_embedding, generated_embedding).item())
        
        # Compute parse accuracy
        if include_accuracy:
            generated_functions = parse_manual_function_call(generated_text)
            gt_functions = parse_manual_function_call(gt_text)
            accuracies.append(generated_functions == gt_functions)
    
    # Save metrics to output directory
    with open(output_dir, 'w') as file:
        mr = metrics.compute()
        bertscores = bertscore.compute(lang='en')
        bertscores.pop('hashcode')  # Remove hashcode from results
        bertscores = {f'bertscore_{k}': np.mean(v) for k, v in bertscores.items()}
        mr.update(bertscores)
        mr['semantic_similarity'] = np.mean(semantic_similarities)
        if include_accuracy:
            mr['accuracy'] = np.mean(accuracies)
        json.dump(mr, file, indent=4)
    
    # Clean up
    del base_model
    del fine_tuned_model
    del tokenizer
    del eval_model
    torch.cuda.empty_cache()
    gc.collect()

In [4]:
def evaluate_dpo_model(model_id, model_dir, eval_dataset, output_dir, include_accuracy=True):
    # Load the fine-tuned model and tokenizer
    base_model = AutoModelForCausalLM.from_pretrained(model_id, dtype=torch.bfloat16, device_map="auto")
    fine_tuned_model = PeftModel.from_pretrained(base_model, model_dir)
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    eval_model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
    
    # Define evaluation metrics
    metrics = evaluate.combine(['bleu', 'rouge', 'meteor'])
    bertscore = evaluate.load('bertscore')
    semantic_similarities = []
    if include_accuracy:
        accuracies = []

    for instance in tqdm(eval_dataset):
        # Tokenize input
        text = tokenizer.apply_chat_template(
            instance["prompt"], add_generation_prompt=True, tokenize=False
        )
        model_inputs = tokenizer([text], return_tensors="pt").to(fine_tuned_model.device)

        # Generate response
        generated_ids = fine_tuned_model.generate(
            **model_inputs,
            max_new_tokens=2048
        )
        output_ids = generated_ids[0][len(model_inputs.input_ids[0]):]

        # Decode and extract model response
        generated_text = tokenizer.decode(output_ids, skip_special_tokens=True)
        
        # Get the ground truth response
        gt_text = instance['chosen'][0]['content']
        
        # Compute semantic similarity
        gt_embedding = eval_model.encode(gt_text, convert_to_tensor=True)
        generated_embedding = eval_model.encode(generated_text, convert_to_tensor=True)

        # Compute metrics against the reference response
        metrics.add(prediction=generated_text, reference=gt_text)
        bertscore.add(prediction=generated_text, reference=gt_text)
        semantic_similarities.append(util.pytorch_cos_sim(gt_embedding, generated_embedding).item())
        
        # Compute parse accuracy
        if include_accuracy:
            generated_functions = parse_manual_function_call(generated_text)
            gt_functions = parse_manual_function_call(gt_text)
            accuracies.append(generated_functions == gt_functions)
    
    # Save metrics to output directory
    with open(output_dir, 'w') as file:
        mr = metrics.compute()
        bertscores = bertscore.compute(lang='en')
        bertscores.pop('hashcode')  # Remove hashcode from results
        bertscores = {f'bertscore_{k}': np.mean(v) for k, v in bertscores.items()}
        mr.update(bertscores)
        mr['semantic_similarity'] = np.mean(semantic_similarities)
        if include_accuracy:
            mr['accuracy'] = np.mean(accuracies)
        json.dump(mr, file, indent=4)
    
    # Clean up
    del base_model
    del fine_tuned_model
    del tokenizer
    del eval_model
    torch.cuda.empty_cache()
    gc.collect()

# SFT

## Prepare data

In [71]:
def preprocess_function(example):
    return {
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT_CODE},
            {"role": "user", "content": example['prompt']},
            {"role": "assistant", "content": example['correct']}
        ]
    }

In [72]:
with open("data/generated_data.json", "r") as f:
    data = json.load(f)
dataset = Dataset.from_list(data).map(preprocess_function, remove_columns=["prompt", "correct", "incorrect"]).train_test_split(test_size=0.2, seed=42)

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Map: 100%|██████████| 1000/1000 [00:00<00:00, 27587.21 examples/s]

In [73]:
dataset["train"][0]

{'messages': [{'content': 'You control a Kinova Gen3 robotic arm in Unity. Be concise and direct.\nThink step by step about the functions you need to call and the arguments they require to fully complete the user\'s request.\nEnsure that you are calling all functions necessary in the right order to achieve the desired outcome.\nThe current state of the simulation, including the names, positions, and rotations of all objects, is provided in JSON form in your most recent assistant message.\n\n## ⚠️ CRITICAL: Coordinate System\nUnity uses: **X = left/right, Y = UP/DOWN (vertical), Z = forward/back**\n- Move UP → increase Y (y > 0)\n- Move DOWN → decrease Y (y < 0)\n- Move LEFT → decrease X (x < 0)\n- Move RIGHT → increase X (x > 0)\n- Move FORWARD → increase Z (z > 0)\n- Move BACKWARD → decrease Z (z < 0)\n\n## CRITICAL: Function Call Format\n\nWhen you need to call a function, output ONLY this JSON format (nothing else):\n```json\n{"function": "function_name", "args": {"param": "value"}}\n```\n\n## Available Functions:\n\n### get_info(name=None)\nGet scene objects and positions.\n```json\n{"function": "get_info", "args": {}}                    // Get all objects\n{"function": "get_info", "args": {"name": "Banana"}}    // Find specific object\n```\n\n### move_to_object(name, offset_x=0, offset_y=0.1, offset_z=0, duration=2.0)\nMove to object with offset.\n```json\n{"function": "move_to_object", "args": {"name": "Banana", "offset_y": 0.2}}\n```\n\n### grasp_object(name, lift_height=0.5)\nGrasp object using magnetic attachment. Process: 1) Move to 10cm above object, 2) Attach magnetically, 3) Wait 2s to stabilize, 4) Lift.\n```json\n{"function": "grasp_object", "args": {"name": "Banana"}}\n{"function": "grasp_object", "args": {"name": "Banana", "lift_height": 0.3}}\n```\n\n### release_object(lift_before_release=True, lift_height=0.1)\nRelease grasped object. It will fall due to gravity.\n```json\n{"function": "release_object", "args": {}}\n{"function": "release_object", "args": {"lift_before_release": false}}\n```\n\n### move_to_position(x, y, z, duration=2.0, relative=False)\nMove to position. **⚠️ REMEMBER: Y is UP/DOWN (vertical), NOT Z!**\n```json\n{"function": "move_to_position", "args": {"x": 0.5, "y": 1.2, "z": 0.3}}              // Absolute position\n{"function": "move_to_position", "args": {"x": 0, "y": 0.2, "z": 0, "relative": true}} // Move UP 20cm (Y-axis!)\n{"function": "move_to_position", "args": {"x": 0, "y": -0.2, "z": 0, "relative": true}} // Move DOWN 20cm (Y-axis!)\n{"function": "move_to_position", "args": {"x": 0.1, "y": 0, "z": 0, "relative": true}} // Move RIGHT 10cm (X-axis)\n{"function": "move_to_position", "args": {"x": -0.1, "y": 0, "z": 0, "relative": true}} // Move LEFT 10cm (X-axis)\n{"function": "move_to_position", "args": {"x": 0, "y": 0, "z": 0.15, "relative": true}} // Move FORWARD 15cm (Z-axis)\n```\n\n## Examples:\n\nUser: "show me all objects"\n→ Output: ```json\n{"function": "get_info", "args": {}}\n```\n\nUser: "where are the bananas"\n→ Output: ```json\n{"function": "get_info", "args": {"name": "Banana"}}\n```\n\nUser: "move to banana 1"\n→ Output: ```json\n{"function": "move_to_object", "args": {"name": "Banana 1"}}\n```\n\nUser: "move up 20cm"\n→ Output: ```json\n{"function": "move_to_position", "args": {"x": 0, "y": 0.2, "z": 0, "relative": true}}\n```\n\nUser: "move down 25cm"\n→ Output: ```json\n{"function": "move_to_position", "args": {"x": 0, "y": -0.25, "z": 0, "relative": true}}\n```\n\nUser: "move right 10cm"\n→ Output: ```json\n{"function": "move_to_position", "args": {"x": 0.1, "y": 0, "z": 0, "relative": true}}\n```\n\nUser: "move forward 15cm"\n→ Output: ```json\n{"function": "move_to_position", "args": {"x": 0, "y": 0, "z": 0.15, "relative": true}}\n```\n\n## Rules:\n1. ALWAYS output function calls in JSON format\n2. NO extra text before or after JSON\n3. **⚠️ CRITICAL COORDINATE SYSTEM - Y IS VERTICAL (UP/DOWN), NOT Z!**\n   - "move up" / "go up" / "higher" → **y > 0** (increase Y)\n   - "move down" / "go down" / "lower" → **y < 0** (decrease Y)\n   - "move left" → x < 0\n   - "move right" → x > 0\n   - "move forward" → z > 0\n   - "move backward" / "move back" → z < 0\n4. **NEVER use Z-axis for up/down movement! Always use Y-axis!**\n',
   'role': 'system'},
  {'content': 'move [-0.12, 0.32, -0.83] relative in 3.38s, move to Banana 3 with offset [0.25, -0.58, -0.49]',
   'role': 'user'},
  {'content': '{"function": "move_to_position", "args": {"x": -0.12, "y": 0.32, "z": -0.83, "relative": true, "duration": 3.38}}\n{"function": "move_to_object", "args": {"name": "Banana 3", "offset_x": 0.25, "offset_y": -0.58, "offset_z": -0.49}}',
   'role': 'assistant'}]}

## Train model

In [74]:
model_id = "Qwen/Qwen2.5-Coder-7B-Instruct"
output_dir = "coder_model_sft"

In [75]:
peft_config = LoraConfig(task_type=TaskType.CAUSAL_LM, r=32, lora_alpha=32)

In [76]:
training_args = SFTConfig(
    # Training schedule / optimization
    per_device_train_batch_size = 4,      # Batch size per GPU
    # gradient_accumulation_steps = 4,      # Gradients are accumulated over multiple steps → effective batch size = 2 * 8 = 16
    warmup_steps = 5,
    num_train_epochs = 1,               # Number of full dataset passes. For shorter training, use `max_steps` instead (this case)
    # max_steps = 100,
    learning_rate = 1e-4,                 # Learning rate for the optimizer
    optim = "adamw_torch",           # Optimizer

    # Logging / reporting
    # logging_steps=1,                      # Log training metrics every N steps
    # report_to="trackio",                  # Experiment tracking tool
    # trackio_space_id=output_dir,          # HF Space where the experiment tracking will be saved
    output_dir='training_checkpoints',                     # Where to save model checkpoints and logs

    max_length=2048,                      # Maximum input sequence length
    # use_liger_kernel=True,                # Enable Liger kernel optimizations for faster training
    activation_offloading=True,           # Offload activations to CPU to reduce GPU memory usage

    # Hub integration
    # push_to_hub=True,                     # Automatically push the trained model to the Hugging Face Hub
                                          # The model will be saved under your Hub account in the repository named `output_dir`

)

In [77]:
model = AutoModelForCausalLM.from_pretrained(model_id, dtype=torch.bfloat16)

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset["train"],
    peft_config=peft_config
)

Loading weights: 100%|██████████| 339/339 [00:00<00:00, 1185.21it/s, Materializing param=model.norm.weight]
Tokenizing train dataset: 100%|██████████| 800/800 [00:01<00:00, 440.39 examples/s]
Truncating train dataset: 100%|██████████| 800/800 [00:00<00:00, 89378.38 examples/s]
WARNING:accelerate.utils.other:Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

In [78]:
trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

TrainOutput(global_step=200, training_loss=0.21961687862873078, metrics={'train_runtime': 422.1306, 'train_samples_per_second': 1.895, 'train_steps_per_second': 0.474, 'total_flos': 5.493097165387776e+16, 'train_loss': 0.21961687862873078})

## Save Model

In [80]:
trainer.save_model(output_dir)

In [81]:
if 'model' in globals():
    del globals()['model']
if 'trainer' in globals():
    del globals()['trainer']
torch.cuda.empty_cache()
gc.collect()

15276

## Evaluate Model

In [82]:
evaluate_sft_model(model_id, output_dir, dataset["test"], "results/coder_sft.json")

Loading weights: 100%|██████████| 339/339 [00:01<00:00, 181.28it/s, Materializing param=model.norm.weight]
[nltk_data] Downloading package wordnet to /home/jmwood23/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/jmwood23/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /home/jmwood23/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
100%|██████████| 200/200 [11:52<00:00,  3.56s/it]

# DPO

## Prepare data

In [19]:
def preprocess_function(example):
    return {
        "prompt": [
            {"role": "system", "content": SYSTEM_PROMPT_CODE},
            {"role": "user", "content": example['prompt']}
        ],
        "chosen": [{"role": "assistant", "content": example['correct']}],
        "rejected": [{"role": "assistant", "content": example['incorrect']}]
    }

In [ ]:
with open("data/generated_data.json", "r") as f:
    data = json.load(f)
dataset = Dataset.from_list(data).map(preprocess_function, remove_columns=["correct", "incorrect"]).train_test_split(test_size=0.2, seed=42)

Map: 100%|██████████| 1000/1000 [00:00<00:00, 18297.60 examples/s]

In [21]:
dataset["train"][0]

{'prompt': [{'content': 'You control a Kinova Gen3 robotic arm in Unity. Be concise and direct.\nThink step by step about the functions you need to call and the arguments they require to fully complete the user\'s request.\nEnsure that you are calling all functions necessary in the right order to achieve the desired outcome.\nThe current state of the simulation, including the names, positions, and rotations of all objects, is provided in JSON form in your most recent assistant message.\n\n## ⚠️ CRITICAL: Coordinate System\nUnity uses: **X = left/right, Y = UP/DOWN (vertical), Z = forward/back**\n- Move UP → increase Y (y > 0)\n- Move DOWN → decrease Y (y < 0)\n- Move LEFT → decrease X (x < 0)\n- Move RIGHT → increase X (x > 0)\n- Move FORWARD → increase Z (z > 0)\n- Move BACKWARD → decrease Z (z < 0)\n\n## CRITICAL: Function Call Format\n\nWhen you need to call a function, output ONLY this JSON format (nothing else):\n```json\n{"function": "function_name", "args": {"param": "value"}}\n```\n\n## Available Functions:\n\n### get_info(name=None)\nGet scene objects and positions.\n```json\n{"function": "get_info", "args": {}}                    // Get all objects\n{"function": "get_info", "args": {"name": "Banana"}}    // Find specific object\n```\n\n### move_to_object(name, offset_x=0, offset_y=0.1, offset_z=0, duration=2.0)\nMove to object with offset.\n```json\n{"function": "move_to_object", "args": {"name": "Banana", "offset_y": 0.2}}\n```\n\n### grasp_object(name, lift_height=0.5)\nGrasp object using magnetic attachment. Process: 1) Move to 10cm above object, 2) Attach magnetically, 3) Wait 2s to stabilize, 4) Lift.\n```json\n{"function": "grasp_object", "args": {"name": "Banana"}}\n{"function": "grasp_object", "args": {"name": "Banana", "lift_height": 0.3}}\n```\n\n### release_object(lift_before_release=True, lift_height=0.1)\nRelease grasped object. It will fall due to gravity.\n```json\n{"function": "release_object", "args": {}}\n{"function": "release_object", "args": {"lift_before_release": false}}\n```\n\n### move_to_position(x, y, z, duration=2.0, relative=False)\nMove to position. **⚠️ REMEMBER: Y is UP/DOWN (vertical), NOT Z!**\n```json\n{"function": "move_to_position", "args": {"x": 0.5, "y": 1.2, "z": 0.3}}              // Absolute position\n{"function": "move_to_position", "args": {"x": 0, "y": 0.2, "z": 0, "relative": true}} // Move UP 20cm (Y-axis!)\n{"function": "move_to_position", "args": {"x": 0, "y": -0.2, "z": 0, "relative": true}} // Move DOWN 20cm (Y-axis!)\n{"function": "move_to_position", "args": {"x": 0.1, "y": 0, "z": 0, "relative": true}} // Move RIGHT 10cm (X-axis)\n{"function": "move_to_position", "args": {"x": -0.1, "y": 0, "z": 0, "relative": true}} // Move LEFT 10cm (X-axis)\n{"function": "move_to_position", "args": {"x": 0, "y": 0, "z": 0.15, "relative": true}} // Move FORWARD 15cm (Z-axis)\n```\n\n## Examples:\n\nUser: "show me all objects"\n→ Output: ```json\n{"function": "get_info", "args": {}}\n```\n\nUser: "where are the bananas"\n→ Output: ```json\n{"function": "get_info", "args": {"name": "Banana"}}\n```\n\nUser: "move to banana 1"\n→ Output: ```json\n{"function": "move_to_object", "args": {"name": "Banana 1"}}\n```\n\nUser: "move up 20cm"\n→ Output: ```json\n{"function": "move_to_position", "args": {"x": 0, "y": 0.2, "z": 0, "relative": true}}\n```\n\nUser: "move down 25cm"\n→ Output: ```json\n{"function": "move_to_position", "args": {"x": 0, "y": -0.25, "z": 0, "relative": true}}\n```\n\nUser: "move right 10cm"\n→ Output: ```json\n{"function": "move_to_position", "args": {"x": 0.1, "y": 0, "z": 0, "relative": true}}\n```\n\nUser: "move forward 15cm"\n→ Output: ```json\n{"function": "move_to_position", "args": {"x": 0, "y": 0, "z": 0.15, "relative": true}}\n```\n\n## Rules:\n1. ALWAYS output function calls in JSON format\n2. NO extra text before or after JSON\n3. **⚠️ CRITICAL COORDINATE SYSTEM - Y IS VERTICAL (UP/DOWN), NOT Z!**\n   - "move up" / "go up" / "higher" → **y > 0** (increase Y)\n   - "move down" / "go down" / "lower" → **y < 0** (decrease Y)\n   - "move left" → x < 0\n   - "move right" → x > 0\n   - "move forward" → z > 0\n   - "move backward" / "move back" → z < 0\n4. **NEVER use Z-axis for up/down movement! Always use Y-axis!**\n',
   'role': 'system'},
  {'content': 'move [-0.12, 0.32, -0.83] relative in 3.38s, move to Banana 3 with offset [0.25, -0.58, -0.49]',
   'role': 'user'}],
 'chosen': [{'content': '{"function": "move_to_position", "args": {"x": -0.12, "y": 0.32, "z": -0.83, "relative": true, "duration": 3.38}}\n{"function": "move_to_object", "args": {"name": "Banana 3", "offset_x": 0.25, "offset_y": -0.58, "offset_z": -0.49}}',
   'role': 'assistant'}],
 'rejected': [{'content': '{"function": "move_to_position", "args": {"x": -0.12, "y": 0.32, "z": -0.83, "relative": true, "duration": 3.38}}\n{"function": "move_to_object", "args": {"name": "Banana 3", "offset_x": 0.25, "offset_y": -0.58, "offset_z": -0.49}}',
   'role': 'assistant'}]}

## Train model

In [22]:
model_id = "Qwen/Qwen2.5-Coder-7B-Instruct"
output_dir = "coder_model_dpo"

In [23]:
peft_config = LoraConfig(task_type=TaskType.CAUSAL_LM, r=32, lora_alpha=32)

In [24]:
training_args = DPOConfig(
    beta=0.1,
    # Training schedule / optimization
    per_device_train_batch_size = 4,      # Batch size per GPU
    # gradient_accumulation_steps = 4,      # Gradients are accumulated over multiple steps → effective batch size = 2 * 8 = 16
    warmup_steps = 5,
    num_train_epochs = 1,               # Number of full dataset passes. For shorter training, use `max_steps` instead (this case)
    # max_steps = 100,
    learning_rate = 1e-4,                 # Learning rate for the optimizer
    optim = "adamw_torch",           # Optimizer

    # Logging / reporting
    # logging_steps=1,                      # Log training metrics every N steps
    # report_to="trackio",                  # Experiment tracking tool
    # trackio_space_id=output_dir,          # HF Space where the experiment tracking will be saved
    output_dir='training_checkpoints',                     # Where to save model checkpoints and logs

    max_length=2048,                      # Maximum input sequence length
    # use_liger_kernel=True,                # Enable Liger kernel optimizations for faster training

    # Hub integration
    # push_to_hub=True,                     # Automatically push the trained model to the Hugging Face Hub
                                          # The model will be saved under your Hub account in the repository named `output_dir`
)

In [25]:
model = AutoModelForCausalLM.from_pretrained(model_id, dtype=torch.bfloat16)

trainer = DPOTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset["train"],
    peft_config=peft_config
)

Loading weights: 100%|██████████| 339/339 [00:00<00:00, 1008.56it/s, Materializing param=model.norm.weight]
Extracting prompt in train dataset: 100%|██████████| 800/800 [00:00<00:00, 4624.92 examples/s]
Applying chat template to train dataset: 100%|██████████| 800/800 [00:00<00:00, 818.48 examples/s]
Tokenizing train dataset: 100%|██████████| 800/800 [00:01<00:00, 423.94 examples/s]
WARNING:accelerate.utils.other:Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

In [26]:
trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

TrainOutput(global_step=200, training_loss=0.22019098252058028, metrics={'train_runtime': 347.2911, 'train_samples_per_second': 2.304, 'train_steps_per_second': 0.576, 'total_flos': 0.0, 'train_loss': 0.22019098252058028, 'epoch': 1.0})

## Save Model

In [27]:
trainer.save_model(output_dir)

In [28]:
if 'model' in globals():
    del globals()['model']
if 'trainer' in globals():
    del globals()['trainer']
torch.cuda.empty_cache()
gc.collect()

15043

## Evaluate Model

In [32]:
evaluate_dpo_model(model_id, output_dir, dataset["test"], "results/coder_dpo.json")

Loading weights: 100%|██████████| 339/339 [00:02<00:00, 169.34it/s, Materializing param=model.norm.weight]
[nltk_data] Downloading package wordnet to /home/jmwood23/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/jmwood23/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /home/jmwood23/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
100%|██████████| 200/200 [12:42<00:00,  3.81s/it]

# Model inference

In [13]:
base_model = AutoModelForCausalLM.from_pretrained(model_id, dtype=torch.bfloat16, device_map="auto")
tokenizer = AutoTokenizer.from_pretrained(model_id)

Loading weights: 100%|██████████| 339/339 [00:01<00:00, 175.73it/s, Materializing param=model.norm.weight]

In [14]:
messages = [
  {
      'content': SYSTEM_PROMPT_CODE,
      'role': 'system',
  },
  {
      'content': "Move the gripper down and to the right by 20cm, down and to the left by 20cm, up and to the left by 20cm, and up and to the right by 20cm.",
      'role': 'user',
  }
]

In [ ]:
text = tokenizer.apply_chat_template(
    messages, add_generation_prompt=True, tokenize=False
)
model_inputs = tokenizer([text], return_tensors="pt").to(base_model.device)

generated_ids = base_model.generate(
    **model_inputs,
    max_new_tokens=2048
)
output_ids = generated_ids[0][len(model_inputs.input_ids[0]):]

# Decode and extract model response
generated_text = tokenizer.decode(output_ids, skip_special_tokens=True)
print(generated_text)

In [16]:
fine_tuned_model = PeftModel.from_pretrained(base_model, output_dir)

In [17]:
text = tokenizer.apply_chat_template(
    messages, add_generation_prompt=True, tokenize=False
)
model_inputs = tokenizer([text], return_tensors="pt").to(fine_tuned_model.device)

generated_ids = fine_tuned_model.generate(
    **model_inputs,
    max_new_tokens=512
)
output_ids = generated_ids[0][len(model_inputs.input_ids[0]):]

# Decode and extract model response
generated_text = tokenizer.decode(output_ids, skip_special_tokens=True)
print(generated_text)

```json
{"function": "move_to_position", "args": {"x": 0, "y": -0.2, "z": 0, "relative": true}} // Move DOWN 20cm (Y-axis!)
{"function": "move_to_position", "args": {"x": 0.2, "y": 0, "z": 0, "relative": true}} // Move RIGHT 20cm (X-axis)
{"function": "move_to_position", "args": {"x": 0, "y": -0.2, "z": 0, "relative": true}} // Move DOWN 20cm (Y-axis!)
{"function": "move_to_position", "args": {"x": -0.2, "y": 0, "z": 0, "relative": true}} // Move LEFT 20cm (X-axis)
{"function": "move_to_position", "args": {"x": 0, "y": 0.2, "z": 0, "relative": true}}  // Move UP 20cm (Y-axis!)
{"function": "move_to_position", "args": {"x": -0.2, "y": 0, "z": 0, "relative": true}} // Move LEFT 20cm (X-axis)
{"function": "move_to_position", "args": {"x": 0, "y": 0.2, "z": 0, "relative": true}}  // Move UP 20cm (Y-axis!)
{"function": "move_to_position", "args": {"x": 0.2, "y": 0, "z": 0, "relative": true}} // Move RIGHT 20cm (X-axis)
```

# Evaluator SFT

## Prepare data

In [10]:
def preprocess_function(example):
    return {
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT_EVAL},
            {"role": "user", "content": example['prompt']},
            {"role": "assistant", "content": example['better']}
        ]
    }

In [11]:
with open("data/generated_data.json", "r") as f:
    data = json.load(f)
with open("data/generated_responses.json", "r") as f:
    responses = json.load(f)
    
for i, r in enumerate(responses):
    r["prompt"] = f"User Request: {data[i]['prompt']}\nCode: {data[i]['incorrect']}"
dataset = Dataset.from_list(responses).map(preprocess_function, remove_columns=["bad", "good", "better", "prompt"]).train_test_split(test_size=0.2, seed=42)

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Map: 100%|██████████| 1000/1000 [00:00<00:00, 24456.16 examples/s]

In [12]:
dataset["train"][0]

{'messages': [{'content': 'You are an agent evaluating the functional correctness of robot simulation code. Be concise and direct.\nEnsure that all functions necessary to achieve the user\'s request are present and being called in the correct order.\nAlso ensure that the correct arguments to fulfill the user\'s request are being passed into functions.\nMake sure that the direction for movement-based functions is correct as well.\nIf the necessary functions are present, the order of the code matches the user\'s request, and the correct arguments are being passed to each function, output \'True\' and nothing else. \nOtherwise, output \'False\', state the errors in the code, and provide suggestions for fixing the function calls and/or arguments.\nThe current state of the simulation, including the names, positions, and rotations of all objects, is provided in JSON form in your most recent assistant message.\n\n# ⚠️ CRITICAL: Coordinate System\nUnity uses: **X = left/right, Y = UP/DOWN (vertical), Z = forward/back**\n- Move UP → increase Y (y > 0)\n- Move DOWN → decrease Y (y < 0)\n- Move LEFT → decrease X (x < 0)\n- Move RIGHT → increase X (x > 0)\n- Move FORWARD → increase Z (z > 0)\n- Move BACKWARD → decrease Z (z < 0)\n\n# Example Inputs and Outputs\n\n## Example 1\n\n### Input\nUser Request: Move the gripper down and to the right by 20cm, down and to the left by 20cm, up and to the left by 20cm, and up and to the right by 20cm\nCode:\n```json\n{"function": "move_to_position", "args": {"x": -0.2, "y": -0.2, "z": 0, "relative": true}}\n{"function": "move_to_position", "args": {"x": 0.2, "y": -0.2, "z": 0, "relative": true}}\n{"function": "move_to_position", "args": {"x": -0.2, "y": 0.2, "z": 0, "relative": true}}\n{"function": "move_to_position", "args": {"x": 0.2, "y": 0.2, "z": 0, "relative": true}}\n```\n\n### Output\nFalse\nErrors: This code moves down and to the left and then moves down and to the right, but the user requested that the gripper moves down and to the right before moving down and to the left.\nSuggestions: Swap the order of the first 2 functions.\n\n## Example 2\n\n### Input\nUser Request: Move to Banana 1 and then grasp it\nCode:\n```json\n{"function": "move_to_object", "args": {"name": "Banana 1"}}\n```\n\n### Output\nFalse\nErrors: The code for grasping the banana is missing.\nSuggestions: Call the "grasp_object" function with "Banana 1" as the object parameter after the "move_to_object" function.\n\n## Example 3\n\n### Input\nUser Request: Grasp the object, move to the left 25cm, then release the object\nCode:\n```json\n{"function": "grasp_object", "args": {"name": "Banana 1"}}\n{"function": "move_to_position", "args": {"x": -0.25, "y": 0, "z": 0, "relative": true}}\n{"function": "release_object", "args": {}}\n```\n\n### Output\nTrue\n\n## Example 4\n\n### Input\nUser Request: Move up 15cm\nCode:\n```json\n{"function": "move_to_position", "args": {"x": 0, "y": 0.15, "z": 0, "relative": true}}\n```\n\n### Output\nTrue\n\n## Example 5\n\n### Input\nUser Request: Move to the right 40cm\nCode:\n```json\n{"function": "move_to_position", "args": {"x": 0.2, "y": 0, "z": 0, "relative": true}}\n```\n\n### Output\nFalse\nErrors: The distance provided for x is incorrect, it should be 40cm or 0.4m.\nSuggestions: Change the argument for x to 0.4\n\n## Example 6\n\n### Input\nUser Request: Move to the left 40cm\nCode:\n```json\n{"function": "move_to_position", "args": {"x": 0.4, "y": 0, "z": 0, "relative": true}}\n```\n\n### Output\nFalse\nErrors: The argument for x is positive so this code moves the gripper to the right, not left.\nSuggestions: Change the argument for x to -0.4\n',
   'role': 'system'},
  {'content': 'User Request: move [-0.12, 0.32, -0.83] relative in 3.38s, move to Banana 3 with offset [0.25, -0.58, -0.49]\nCode: {"function": "move_to_position", "args": {"x": -0.12, "y": 0.32, "z": -0.83, "relative": true, "duration": 3.38}}\n{"function": "move_to_object", "args": {"name": "Banana 3", "offset_x": 0.25, "offset_y": -0.58, "offset_z": -0.49}}',
   'role': 'user'},
  {'content': 'False  \nErrors:  \n1. The second requested action, "move to Banana 3 with offset [0.25, -0.58, -0.49]", is missing from the code.  \n2. The existing code only performs the first move and then stops.\n\nSuggestions:  \n1. Keep the first function call as-is for the relative move:\n```json\n{"function": "move_to_position", "args": {"x": -0.12, "y": 0.32, "z": -0.83, "duration": 3.38, "relative": true}}\n```\n2. Add a second function call to move to Banana 3 with the specified offset. For example, if the API supports an offset parameter:\n```json\n{"function": "move_to_object", "args": {"name": "Banana 3", "offset": {"x": 0.25, "y": -0.58, "z": -0.49}}}\n```\nIf there is no offset parameter, first move to the object, then apply a relative move:\n```json\n{"function": "move_to_object", "args": {"name": "Banana 3"}}\n{"function": "move_to_position", "args": {"x": 0.25, "y": -0.58, "z": -0.49, "relative": true}}\n```',
   'role': 'assistant'}]}

## Train model

In [13]:
model_id = "Qwen/Qwen2.5-Coder-7B-Instruct"
output_dir = "eval_model_sft"

In [14]:
peft_config = LoraConfig(task_type=TaskType.CAUSAL_LM, r=32, lora_alpha=32)

In [15]:
training_args = SFTConfig(
    # Training schedule / optimization
    per_device_train_batch_size = 4,      # Batch size per GPU
    # gradient_accumulation_steps = 4,      # Gradients are accumulated over multiple steps → effective batch size = 2 * 8 = 16
    warmup_steps = 5,
    num_train_epochs = 1,               # Number of full dataset passes. For shorter training, use `max_steps` instead (this case)
    # max_steps = 100,
    learning_rate = 1e-4,                 # Learning rate for the optimizer
    optim = "adamw_torch",           # Optimizer

    # Logging / reporting
    # logging_steps=1,                      # Log training metrics every N steps
    # report_to="trackio",                  # Experiment tracking tool
    # trackio_space_id=output_dir,          # HF Space where the experiment tracking will be saved
    output_dir='training_checkpoints',                     # Where to save model checkpoints and logs

    max_length=2048,                      # Maximum input sequence length
    # use_liger_kernel=True,                # Enable Liger kernel optimizations for faster training
    activation_offloading=True,           # Offload activations to CPU to reduce GPU memory usage

    # Hub integration
    # push_to_hub=True,                     # Automatically push the trained model to the Hugging Face Hub
                                          # The model will be saved under your Hub account in the repository named `output_dir`

)

In [16]:
model = AutoModelForCausalLM.from_pretrained(model_id, dtype=torch.bfloat16)

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset["train"],
    peft_config=peft_config
)

Loading weights: 100%|██████████| 339/339 [00:05<00:00, 66.30it/s, Materializing param=model.norm.weight]
Tokenizing train dataset: 100%|██████████| 800/800 [00:02<00:00, 353.47 examples/s]
Truncating train dataset: 100%|██████████| 800/800 [00:00<00:00, 83810.65 examples/s]
Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

In [17]:
trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

TrainOutput(global_step=200, training_loss=0.3228657430410385, metrics={'train_runtime': 428.934, 'train_samples_per_second': 1.865, 'train_steps_per_second': 0.466, 'total_flos': 5.676986080002048e+16, 'train_loss': 0.3228657430410385})

## Save model

In [18]:
trainer.save_model(output_dir)

In [19]:
if 'model' in globals():
    del globals()['model']
if 'trainer' in globals():
    del globals()['trainer']
torch.cuda.empty_cache()
gc.collect()

15276

## Evaluate model

In [20]:
evaluate_sft_model(model_id, output_dir, dataset["test"], "results/eval_sft.json", include_accuracy=False)

Loading weights: 100%|██████████| 339/339 [00:02<00:00, 160.12it/s, Materializing param=model.norm.weight]
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 174.49it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[nltk_data] Downloading package wordnet to /home/jmwood23/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/jmwood23/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /home/jmwood23/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
100%|██████████| 200/200 [24:10<00:00,  7.25s/it]
Loading weights: 100%|██████████| 389/389 [00:03<00:00, 124.08it/s, Materializing param=encoder.layer.23.output.dense.weight]
RobertaModel LOAD REPORT from: roberta-large
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
pooler.dense.bias               | MISSING    |
pooler.dense.weight             | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

# Evaluator DPO

## Prepare data

In [24]:
def preprocess_function(example):
    return {
        "prompt": [
            {"role": "system", "content": SYSTEM_PROMPT_EVAL},
            {"role": "user", "content": example['prompt']}
        ],
        "chosen": [{"role": "assistant", "content": example['good']}],
        "rejected": [{"role": "assistant", "content": example['bad']}]
    }

In [27]:
with open("data/generated_data.json", "r") as f:
    data = json.load(f)
with open("data/generated_responses.json", "r") as f:
    responses = json.load(f)
    
for i, r in enumerate(responses):
    r["prompt"] = f"User Request: {data[i]['prompt']}\nCode: {data[i]['incorrect']}"
dataset = Dataset.from_list(responses).map(preprocess_function, remove_columns=["bad", "good", "better"]).train_test_split(test_size=0.2, seed=42)

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Map: 100%|██████████| 1000/1000 [00:00<00:00, 18047.70 examples/s]

In [28]:
dataset['train'][0]

{'prompt': [{'content': 'You are an agent evaluating the functional correctness of robot simulation code. Be concise and direct.\nEnsure that all functions necessary to achieve the user\'s request are present and being called in the correct order.\nAlso ensure that the correct arguments to fulfill the user\'s request are being passed into functions.\nMake sure that the direction for movement-based functions is correct as well.\nIf the necessary functions are present, the order of the code matches the user\'s request, and the correct arguments are being passed to each function, output \'True\' and nothing else. \nOtherwise, output \'False\', state the errors in the code, and provide suggestions for fixing the function calls and/or arguments.\nThe current state of the simulation, including the names, positions, and rotations of all objects, is provided in JSON form in your most recent assistant message.\n\n# ⚠️ CRITICAL: Coordinate System\nUnity uses: **X = left/right, Y = UP/DOWN (vertical), Z = forward/back**\n- Move UP → increase Y (y > 0)\n- Move DOWN → decrease Y (y < 0)\n- Move LEFT → decrease X (x < 0)\n- Move RIGHT → increase X (x > 0)\n- Move FORWARD → increase Z (z > 0)\n- Move BACKWARD → decrease Z (z < 0)\n\n# Example Inputs and Outputs\n\n## Example 1\n\n### Input\nUser Request: Move the gripper down and to the right by 20cm, down and to the left by 20cm, up and to the left by 20cm, and up and to the right by 20cm\nCode:\n```json\n{"function": "move_to_position", "args": {"x": -0.2, "y": -0.2, "z": 0, "relative": true}}\n{"function": "move_to_position", "args": {"x": 0.2, "y": -0.2, "z": 0, "relative": true}}\n{"function": "move_to_position", "args": {"x": -0.2, "y": 0.2, "z": 0, "relative": true}}\n{"function": "move_to_position", "args": {"x": 0.2, "y": 0.2, "z": 0, "relative": true}}\n```\n\n### Output\nFalse\nErrors: This code moves down and to the left and then moves down and to the right, but the user requested that the gripper moves down and to the right before moving down and to the left.\nSuggestions: Swap the order of the first 2 functions.\n\n## Example 2\n\n### Input\nUser Request: Move to Banana 1 and then grasp it\nCode:\n```json\n{"function": "move_to_object", "args": {"name": "Banana 1"}}\n```\n\n### Output\nFalse\nErrors: The code for grasping the banana is missing.\nSuggestions: Call the "grasp_object" function with "Banana 1" as the object parameter after the "move_to_object" function.\n\n## Example 3\n\n### Input\nUser Request: Grasp the object, move to the left 25cm, then release the object\nCode:\n```json\n{"function": "grasp_object", "args": {"name": "Banana 1"}}\n{"function": "move_to_position", "args": {"x": -0.25, "y": 0, "z": 0, "relative": true}}\n{"function": "release_object", "args": {}}\n```\n\n### Output\nTrue\n\n## Example 4\n\n### Input\nUser Request: Move up 15cm\nCode:\n```json\n{"function": "move_to_position", "args": {"x": 0, "y": 0.15, "z": 0, "relative": true}}\n```\n\n### Output\nTrue\n\n## Example 5\n\n### Input\nUser Request: Move to the right 40cm\nCode:\n```json\n{"function": "move_to_position", "args": {"x": 0.2, "y": 0, "z": 0, "relative": true}}\n```\n\n### Output\nFalse\nErrors: The distance provided for x is incorrect, it should be 40cm or 0.4m.\nSuggestions: Change the argument for x to 0.4\n\n## Example 6\n\n### Input\nUser Request: Move to the left 40cm\nCode:\n```json\n{"function": "move_to_position", "args": {"x": 0.4, "y": 0, "z": 0, "relative": true}}\n```\n\n### Output\nFalse\nErrors: The argument for x is positive so this code moves the gripper to the right, not left.\nSuggestions: Change the argument for x to -0.4\n',
   'role': 'system'},
  {'content': 'User Request: move [-0.12, 0.32, -0.83] relative in 3.38s, move to Banana 3 with offset [0.25, -0.58, -0.49]\nCode: {"function": "move_to_position", "args": {"x": -0.12, "y": 0.32, "z": -0.83, "relative": true, "duration": 3.38}}\n{"function": "move_to_object", "args": {"name": "Banana 3", "offset_x": 0.25, "offset_y": -0.58, "offset_z": -0.49}}',
   'role': 'user'}],
 'chosen': [{'content': 'True', 'role': 'assistant'}],
 'rejected': [{'content': 'True', 'role': 'assistant'}]}

## Train model

In [29]:
model_id = "Qwen/Qwen2.5-Coder-7B-Instruct"
output_dir = "eval_model_dpo"

In [11]:
peft_config = LoraConfig(task_type=TaskType.CAUSAL_LM, r=32, lora_alpha=32)

In [12]:
training_args = DPOConfig(
    beta=0.1,
    # Training schedule / optimization
    per_device_train_batch_size = 4,      # Batch size per GPU
    # gradient_accumulation_steps = 4,      # Gradients are accumulated over multiple steps → effective batch size = 2 * 8 = 16
    warmup_steps = 5,
    num_train_epochs = 1,               # Number of full dataset passes. For shorter training, use `max_steps` instead (this case)
    # max_steps = 100,
    learning_rate = 1e-4,                 # Learning rate for the optimizer
    optim = "adamw_torch",           # Optimizer

    # Logging / reporting
    # logging_steps=1,                      # Log training metrics every N steps
    # report_to="trackio",                  # Experiment tracking tool
    # trackio_space_id=output_dir,          # HF Space where the experiment tracking will be saved
    output_dir='training_checkpoints',                     # Where to save model checkpoints and logs

    max_length=2048,                      # Maximum input sequence length
    # use_liger_kernel=True,                # Enable Liger kernel optimizations for faster training

    # Hub integration
    # push_to_hub=True,                     # Automatically push the trained model to the Hugging Face Hub
                                          # The model will be saved under your Hub account in the repository named `output_dir`
)

In [14]:
model = AutoModelForCausalLM.from_pretrained(model_id, dtype=torch.bfloat16)

trainer = DPOTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset['train'],
    peft_config=peft_config
)

Loading weights: 100%|██████████| 339/339 [00:03<00:00, 88.46it/s, Materializing param=model.norm.weight]
Extracting prompt in train dataset: 100%|██████████| 800/800 [00:00<00:00, 5262.33 examples/s]
Applying chat template to train dataset: 100%|██████████| 800/800 [00:00<00:00, 814.45 examples/s]
Tokenizing train dataset: 100%|██████████| 800/800 [00:01<00:00, 440.22 examples/s]
Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

In [15]:
trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

TrainOutput(global_step=200, training_loss=0.12881084129214287, metrics={'train_runtime': 500.5325, 'train_samples_per_second': 1.598, 'train_steps_per_second': 0.4, 'total_flos': 0.0, 'train_loss': 0.12881084129214287, 'epoch': 1.0})

## Save Model

In [16]:
trainer.save_model(output_dir)

In [17]:
if 'model' in globals():
    del globals()['model']
if 'trainer' in globals():
    del globals()['trainer']
torch.cuda.empty_cache()
gc.collect()

15043

## Evaluate Model

In [30]:
evaluate_dpo_model(model_id, output_dir, dataset["test"], "results/eval_dpo.json", False)

Loading weights: 100%|██████████| 339/339 [00:43<00:00,  7.74it/s, Materializing param=model.norm.weight]
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1311.89it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[nltk_data] Downloading package wordnet to /home/jmwood23/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/jmwood23/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /home/jmwood23/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
100%|██████████| 200/200 [31:16<00:00,  9.38s/it]
Loading weights: 100%|██████████| 389/389 [00:00<00:00, 1242.16it/s, Materializing param=encoder.layer.23.output.dense.weight]
RobertaModel LOAD REPORT from: roberta-large
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
pooler.dense.weight             | MISSING    |
pooler.dense.bias               | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

# Evaluator DPO (GPT Coder-Evaluator Responses)

## Prepare data

In [4]:
def preprocess_function(example):
    return {
        "prompt": [
            {"role": "system", "content": SYSTEM_PROMPT_EVAL},
            {"role": "user", "content": example['prompt']}
        ],
        "chosen": [{"role": "assistant", "content": example['better']}],
        "rejected": [{"role": "assistant", "content": example['bad']}]
    }

In [22]:
with open("data/generated_data.json", "r") as f:
    data = json.load(f)
with open("data/generated_responses.json", "r") as f:
    responses = json.load(f)
    
for i, r in enumerate(responses):
    r["prompt"] = f"User Request: {data[i]['prompt']}\nCode: {data[i]['incorrect']}"
dataset = Dataset.from_list(responses).map(preprocess_function, remove_columns=["bad", "good", "better"]).train_test_split(test_size=0.2, seed=42)

Map: 100%|██████████| 1000/1000 [00:00<00:00, 14801.56 examples/s]

In [9]:
dataset['train'][0]

{'prompt': [{'content': 'You are an agent evaluating the functional correctness of robot simulation code. Be concise and direct.\nEnsure that all functions necessary to achieve the user\'s request are present and being called in the correct order.\nAlso ensure that the correct arguments to fulfill the user\'s request are being passed into functions.\nMake sure that the direction for movement-based functions is correct as well.\nIf the necessary functions are present, the order of the code matches the user\'s request, and the correct arguments are being passed to each function, output \'True\' and nothing else. \nOtherwise, output \'False\', state the errors in the code, and provide suggestions for fixing the function calls and/or arguments.\nThe current state of the simulation, including the names, positions, and rotations of all objects, is provided in JSON form in your most recent assistant message.\n\n# ⚠️ CRITICAL: Coordinate System\nUnity uses: **X = left/right, Y = UP/DOWN (vertical), Z = forward/back**\n- Move UP → increase Y (y > 0)\n- Move DOWN → decrease Y (y < 0)\n- Move LEFT → decrease X (x < 0)\n- Move RIGHT → increase X (x > 0)\n- Move FORWARD → increase Z (z > 0)\n- Move BACKWARD → decrease Z (z < 0)\n\n# Example Inputs and Outputs\n\n## Example 1\n\n### Input\nUser Request: Move the gripper down and to the right by 20cm, down and to the left by 20cm, up and to the left by 20cm, and up and to the right by 20cm\nCode:\n```json\n{"function": "move_to_position", "args": {"x": -0.2, "y": -0.2, "z": 0, "relative": true}}\n{"function": "move_to_position", "args": {"x": 0.2, "y": -0.2, "z": 0, "relative": true}}\n{"function": "move_to_position", "args": {"x": -0.2, "y": 0.2, "z": 0, "relative": true}}\n{"function": "move_to_position", "args": {"x": 0.2, "y": 0.2, "z": 0, "relative": true}}\n```\n\n### Output\nFalse\nErrors: This code moves down and to the left and then moves down and to the right, but the user requested that the gripper moves down and to the right before moving down and to the left.\nSuggestions: Swap the order of the first 2 functions.\n\n## Example 2\n\n### Input\nUser Request: Move to Banana 1 and then grasp it\nCode:\n```json\n{"function": "move_to_object", "args": {"name": "Banana 1"}}\n```\n\n### Output\nFalse\nErrors: The code for grasping the banana is missing.\nSuggestions: Call the "grasp_object" function with "Banana 1" as the object parameter after the "move_to_object" function.\n\n## Example 3\n\n### Input\nUser Request: Grasp the object, move to the left 25cm, then release the object\nCode:\n```json\n{"function": "grasp_object", "args": {"name": "Banana 1"}}\n{"function": "move_to_position", "args": {"x": -0.25, "y": 0, "z": 0, "relative": true}}\n{"function": "release_object", "args": {}}\n```\n\n### Output\nTrue\n\n## Example 4\n\n### Input\nUser Request: Move up 15cm\nCode:\n```json\n{"function": "move_to_position", "args": {"x": 0, "y": 0.15, "z": 0, "relative": true}}\n```\n\n### Output\nTrue\n\n## Example 5\n\n### Input\nUser Request: Move to the right 40cm\nCode:\n```json\n{"function": "move_to_position", "args": {"x": 0.2, "y": 0, "z": 0, "relative": true}}\n```\n\n### Output\nFalse\nErrors: The distance provided for x is incorrect, it should be 40cm or 0.4m.\nSuggestions: Change the argument for x to 0.4\n\n## Example 6\n\n### Input\nUser Request: Move to the left 40cm\nCode:\n```json\n{"function": "move_to_position", "args": {"x": 0.4, "y": 0, "z": 0, "relative": true}}\n```\n\n### Output\nFalse\nErrors: The argument for x is positive so this code moves the gripper to the right, not left.\nSuggestions: Change the argument for x to -0.4\n',
   'role': 'system'},
  {'content': 'User Request: move [-0.12, 0.32, -0.83] relative in 3.38s, move to Banana 3 with offset [0.25, -0.58, -0.49]\nCode: {"function": "move_to_position", "args": {"x": -0.12, "y": 0.32, "z": -0.83, "relative": true, "duration": 3.38}}\n{"function": "move_to_object", "args": {"name": "Banana 3", "offset_x": 0.25, "offset_y": -0.58, "offset_z": -0.49}}',
   'role': 'user'}],
 'chosen': [{'content': 'False  \nErrors:  \n1. The second requested action, "move to Banana 3 with offset [0.25, -0.58, -0.49]", is missing from the code.  \n2. The existing code only performs the first move and then stops.\n\nSuggestions:  \n1. Keep the first function call as-is for the relative move:\n```json\n{"function": "move_to_position", "args": {"x": -0.12, "y": 0.32, "z": -0.83, "duration": 3.38, "relative": true}}\n```\n2. Add a second function call to move to Banana 3 with the specified offset. For example, if the API supports an offset parameter:\n```json\n{"function": "move_to_object", "args": {"name": "Banana 3", "offset": {"x": 0.25, "y": -0.58, "z": -0.49}}}\n```\nIf there is no offset parameter, first move to the object, then apply a relative move:\n```json\n{"function": "move_to_object", "args": {"name": "Banana 3"}}\n{"function": "move_to_position", "args": {"x": 0.25, "y": -0.58, "z": -0.49, "relative": true}}\n```',
   'role': 'assistant'}],
 'rejected': [{'content': 'True', 'role': 'assistant'}]}

## Train model

In [6]:
model_id = "Qwen/Qwen2.5-Coder-7B-Instruct"
output_dir = "eval_model_dpo_gpt"

In [12]:
peft_config = LoraConfig(task_type=TaskType.CAUSAL_LM, r=32, lora_alpha=32)

In [13]:
training_args = DPOConfig(
    beta=0.1,
    # Training schedule / optimization
    per_device_train_batch_size = 4,      # Batch size per GPU
    # gradient_accumulation_steps = 4,      # Gradients are accumulated over multiple steps → effective batch size = 2 * 8 = 16
    warmup_steps = 5,
    num_train_epochs = 1,               # Number of full dataset passes. For shorter training, use `max_steps` instead (this case)
    # max_steps = 100,
    learning_rate = 1e-4,                 # Learning rate for the optimizer
    optim = "adamw_torch",           # Optimizer

    # Logging / reporting
    # logging_steps=1,                      # Log training metrics every N steps
    # report_to="trackio",                  # Experiment tracking tool
    # trackio_space_id=output_dir,          # HF Space where the experiment tracking will be saved
    output_dir='training_checkpoints',                     # Where to save model checkpoints and logs

    max_length=2048,                      # Maximum input sequence length
    # use_liger_kernel=True,                # Enable Liger kernel optimizations for faster training

    # Hub integration
    # push_to_hub=True,                     # Automatically push the trained model to the Hugging Face Hub
                                          # The model will be saved under your Hub account in the repository named `output_dir`
)

In [14]:
model = AutoModelForCausalLM.from_pretrained(model_id, dtype=torch.bfloat16)

trainer = DPOTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset['train'],
    peft_config=peft_config
)

Loading weights: 100%|██████████| 339/339 [00:05<00:00, 62.18it/s, Materializing param=model.norm.weight]
Extracting prompt in train dataset: 100%|██████████| 800/800 [00:00<00:00, 4838.15 examples/s]
Applying chat template to train dataset: 100%|██████████| 800/800 [00:00<00:00, 880.99 examples/s]
Tokenizing train dataset: 100%|██████████| 800/800 [00:01<00:00, 432.75 examples/s]
Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

In [15]:
trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

TrainOutput(global_step=200, training_loss=0.11192882403731347, metrics={'train_runtime': 481.1326, 'train_samples_per_second': 1.663, 'train_steps_per_second': 0.416, 'total_flos': 0.0, 'train_loss': 0.11192882403731347, 'epoch': 1.0})

## Save model

In [16]:
trainer.save_model(output_dir)

In [17]:
if 'model' in globals():
    del globals()['model']
if 'trainer' in globals():
    del globals()['trainer']
torch.cuda.empty_cache()
gc.collect()

15035

## Evaluate model

In [23]:
evaluate_dpo_model(model_id, output_dir, dataset["test"], "results/eval_dpo_gpt.json", False)

Loading weights: 100%|██████████| 339/339 [00:02<00:00, 161.25it/s, Materializing param=model.norm.weight]
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1239.86it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[nltk_data] Downloading package wordnet to /home/jmwood23/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/jmwood23/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /home/jmwood23/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
100%|██████████| 200/200 [31:39<00:00,  9.50s/it]
Loading weights: 100%|██████████| 389/389 [00:00<00:00, 913.91it/s, Materializing param=encoder.layer.23.output.dense.weight]
RobertaModel LOAD REPORT from: roberta-large
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
pooler.dense.weight             | MISSING    |
pooler.dense.bias               | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.